package d.money.mapper.base;

import d.money.pojo.base.SmFunctionInfo;
import d.money.pojo.base.SmFunctionInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmFunctionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int countByExample(SmFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int deleteByExample(SmFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int deleteByPrimaryKey(String functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int insert(SmFunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int insertSelective(SmFunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    List<SmFunctionInfo> selectByExample(SmFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    SmFunctionInfo selectByPrimaryKey(String functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") SmFunctionInfo record, @Param("example") SmFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int updateByExample(@Param("record") SmFunctionInfo record, @Param("example") SmFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int updateByPrimaryKeySelective(SmFunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_function_info
     *
     * @mbggenerated Thu Feb 26 17:58:47 CST 2015
     */
    int updateByPrimaryKey(SmFunctionInfo record);
}